### ISSUE TITLE
Something in client/main is causing createpoints to not work.

### ISSUE THREAD

**Issue by metalanswer** [renzuzu/renzu_evidence#1]
Something in client/main is causing createpoints to not work. Here is the error. I'm messing around to see if I can figure it out.

[   1241140] [b2802_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @renzu_evidence/client/main.lua:224: attempt to call a nil value (global 'Target')^7
[   1241140] [b2802_GTAProce]             MainThrd/ ^3> CreatePoints^7 (^5@renzu_evidence/client/main.lua^7:224)
[   1241140] [b2802_GTAProce]             MainThrd/ ^3> fn^7 (^5@renzu_evidence/client/main.lua^7:254)

**Comment by metalanswer** [comment]
I see what happened, I'm using a bt-target. Ignore my issue. Thanks for all the awesome stuff you put out.

**Comment by renzuzu** [comment]
yea, bt-target is not supported atm,
you could use target = false in config to use ox_lib zones marker
