### ISSUE TITLE
error

### ISSUE THREAD

**Issue by raaazeee** [renzuzu/renzu_evidence#2]
![image](https://user-images.githubusercontent.com/105653892/226943821-b0d43b2b-2779-4130-9e69-2b2938d3d66a.png)
![image](https://user-images.githubusercontent.com/105653892/226943933-cde1902b-ea1f-44ea-a410-c41ab8702b13.png)
meron naman akong item na evidence

**Comment by renzuzu** [comment]
no metadata for sure.

label must be Evidence #12341

**Comment by renzuzu** [comment]
re open if issue still existing... also tell which framework are you using.. since the inv looks like qbcore

**Comment by parham-ebrahim** [comment]
im on QB and i have the same issue
