### ISSUE TITLE
Evidence not showing correct data if using qb-inventory

### ISSUE THREAD

**Issue by parham-ebrahim** [renzuzu/renzu_evidence#5]
So i just got a fresh install in QB...and im having the same issue with metadata.time.
            

  re open if issue still existing... also tell which framework are you using.. since the inv looks like qbcore

_Originally posted by @renzuzu in https://github.com/renzuzu/renzu_evidence/issues/2#issuecomment-1483999607_

**Comment by renzuzu** [comment]
this resource is tested only to my qb-inventory
having label, image, and other item info data (metada) Supported

its a pity that the current qb-inventory is very low technology.

i highly suggest using ox_inventory instead, since you are (FRESH install)

**Comment by parham-ebrahim** [comment]
thank you ... appreciate the info ...
