### ISSUE TITLE
I can't seem to pick up the evidence

### ISSUE THREAD

**Issue by ErinDeveloping** [renzuzu/renzu_evidence#6]
When I use the flashlight to pickup the evidence nothing happends

**Comment by renzuzu** [comment]
make sure the evidence item is registered.

>
When I use the flashlight to pickup the evidence nothing happends

the trigger chance is not 100% if your looking for blips, you should use police job when searching and non police job when testing a evidence trigger.

make sure the Player loaded has triggered too.

this wont work on start resource and test. need a player loaded event from framework
